name: GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Stats
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics-overview.svg
          user: ikrishanaa
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

      - name: Generate Top Languages
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics-languages.svg
          user: ikrishanaa
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 5
          plugin_languages_details: bytes-size, percentage
